version: '3.4'

services:
  php:
    image: 'symfonytypescript/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-dev}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=symfonytypescript-cli'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=${REMOTE_HOST:-172.17.0.1}'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './.git:/srv/.git'
      - './application:/srv/symfonytypescript'
      - './features:/srv/features'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/symfonytypescript'
    command: 'php'
    networks:
      - 'symfonytypescript'

  fpm:
    image: 'symfonytypescript/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-dev}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=symfonytypescript'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
    volumes:
      - './application:/srv/symfonytypescript:rw'
      - './features:/srv/features'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/symfonytypescript'
    command: 'php-fpm -F'
    networks:
      - 'symfonytypescript'

  nginx:
    image: 'nginx:stable-alpine'
    environment:
      APP_ENV: '${APP_ENV:-dev}'
      MAILER_DSN: 'smtp://mailcatcher:1025'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP:-8005}:80'
    volumes:
      - './application:/srv/symfonytypescript:ro'
      - './infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - 'symfonytypescript'

  node:
    image: 'node:lts'
    command: 'yarn encore dev --watch'
    volumes:
      - './application:/srv/symfonytypescript'
      - './features:/srv/features'
      - '~/.cache/yarn:/home/node/.yarn-cache'
    working_dir: '/srv/symfonytypescript'
    networks:
      - 'symfonytypescript'

  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID:-server_id}'
      BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN:-server_token}'
    networks:
      - 'symfonytypescript'

networks:
  symfonytypescript:

